### ISSUE TITLE
T450S install 94360cd

### ISSUE THREAD

**Issue by m4ak** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#1]
Hello, I also have a T450S, the same model and configuration as your 450S, and also black apples, now using your EFI. Ask a few questions to you:
1. What is the T450S BIOS version? Is there any relationship between installing catalina and BIOS version?
2, the specific model of the wireless network card 94360CD, I also want to install one.
3, 94360CD is Apple's network card, you use the adapter card?
4. Now install 10.15 with your EFI. But the black screen cannot wake up after hibernation. Is this still patched?
Please forgive me for these low-level questions, because I am Xiaobai in this respect, and my English is not good, these are translated with google translate. Hope to understand! !

**Comment by dfsnc** [comment]
1. BIOS 版本: 1.36, BIOS ID: jbet72ww. 我不确定BIOS版本是否会影响。
    2, 我的无线网卡 BCM94360CD 0x14e4,0x43a0。(我这张卡在win10和linux下均无法找到网络)
    3, 使用了转接卡, 外加4条IPEX-1端子转IPEX-4座子的线。
2. 在 设置->节能 中取消勾选唤醒以供网络使用和电能小憩，这个会导致唤醒黑屏。(我不是外国人 - . - )

补充一下，转接卡是转ngff的转接卡，[这种](https://item.taobao.com/item.htm?spm=a230r.1.14.117.3f6761fbYvbFmh&id=571047069997&ns=1&abbucket=11#detail)就可以。

**Comment by m4ak** [comment]
你用的 94360CD 加NGFF转接卡才能接在大的槽位（那个大的插槽接WAN卡的那个）？
还是9436CD本身就是NGFF接口的直接插上，然后天线用4条IPEX1 转IPEX4的就OK了？
还有94360cs 94630csax  94360cs2 943602cs 是不是都可以用啊。这型号太多傻傻的分不清啊。



------------------ 原始邮件 ------------------
发件人: "Echo"<notifications@github.com>;
发送时间: 2019年10月21日(星期一) 中午11:59
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "HW"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



 
BIOS 版本: 1.36, BIOS ID: jbet72ww. 我不确定BIOS版本是否会影响。
 2, 我的无线网卡 BCM94360CD 0x14e4,0x43a0。(我这张卡在win10和linux下均无法找到网络)
 3, 使用了转接卡, 外加4条IPEX-1端子转IPEX-4座子的线。
 
在 设置->节能 中取消勾选电能小憩，这个会导致唤醒黑屏。(我不是外国人 - . - )

**Comment by dfsnc** [comment]
之能装到电脑本来安装无线网卡的那个槽位，WAN那个槽位装SSD，94360CD是苹果拆机卡，插头和一般的ngff 网卡不一样，所以要用转接卡，而94360cd是苹果imac上用的，天线接口不同，所以要用天线转接线，94360cd本身比较大，还是4天线的，所以理论上其他几个型号的拆机卡也是可以用在T450s上的，不过我之前试过943602cs，它的蓝牙不能驱动，可能是我买的卡的蓝牙芯片不支持。
我[这里](https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/blob/master/Install%20BCM94360CD%20on%20Thinkpad%20T450s.md)有安装图片，你可以参考一下。

**Comment by m4ak** [comment]
看明白了，把转接卡固定，我一直想成把网卡固定。但是网卡还长放不下，也固定不了，我wan 卡的地方空着呢。ssd 走的是sata 接口，ngff 的都空着呢。还有这转接卡稳定不，淘宝上随便买就可以了吧------------------ 原始邮件 ------------------
发件人: "Echo"<notifications@github.com>
发送时间: 2019年10月25日(星期五) 上午9:44
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



之能装到电脑本来安装无线网卡的那个槽位，WAN那个槽位装SSD，94360CD是苹果拆机卡，插头和一般的ngff 网卡不一样，所以要用转接卡，而94360cd是苹果imac上用的，天线接口不同，所以要用天线转接线，94360cd本身比较大，还是4天线的，所以理论上其他几个型号的拆机卡也是可以用在T450s上的，不过我之前试过943602cs，它的蓝牙不能驱动，可能是我买的卡的蓝牙芯片不支持。
 我这里有安装图片，你可以参考一下。
 
&mdash;

**Comment by dfsnc** [comment]
这个转接卡挺稳定的，转接卡在某宝上好像有多个版本的，我测试过两个版本的，效果一样，你可以直接搜 bcm94360cd ngff 转接卡

**Comment by m4ak** [comment]
收到 搜了一下  诺方恒科  这家店。QQ群里也推荐过。我看看先搞到94360CS 试试你说的驱动的问题。主要是我双系统WIN10也要用。




------------------ 原始邮件 ------------------
发件人: "Echo"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 上午9:58
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "HW"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)




这个转接卡挺稳定的，转接卡在某宝上好像有多个版本的，我测试过两个版本的，效果一样，你可以直接搜 bcm94360cd ngff 转接卡

**Comment by dfsnc** [comment]
我也在这家买的😂
网卡在win10下的问题查资料说是由中断请求(IRQ)引起的，在win10下目前无解，只有linux下有解决方法。

**Comment by m4ak** [comment]
那我先试试cs 看看WIN10搞得了不。不行我就得用DW1820A或者 1560了。




------------------ 原始邮件 ------------------
发件人: "Echo"<notifications@github.com>;
发送时间: 2019年10月25日(星期五) 上午10:15
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "HW"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)




我也在这家买的😂
 网卡在win10下的问题查资料说是由中断请求(IRQ)引起的，在win10下目前无解，只有linux下有解决方法。

**Comment by recmess** [comment]
> 那我先试试cs 看看WIN10搞得了不。不行我就得用DW1820A或者 1560了。
我的需求跟你一样，也要在win10下用，你测试成功没有？

**Comment by recmess** [comment]
我的需求跟你一样，也要在win10下用，你测试成功没有？

**Comment by m4ak** [comment]
还没买到呢，测试成功告诉你------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年10月26日(星期六) 上午8:32
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



我的需求跟你一样，也要在win10下用，你测试成功没有？
 
&mdash;

**Comment by m4ak** [comment]
DW1820a 要买序列号是0vw3t3这样的08kpf4的驱动不起来，而且不需要屏蔽针脚。
------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>;
发送时间: 2019年10月26日(星期六) 上午8:31
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "HW"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



 
那我先试试cs 看看WIN10搞得了不。不行我就得用DW1820A或者 1560了。
 我的需求跟你一样，也要在win10下用，你测试成功没有？

**Comment by recmess** [comment]
驱动不起来是指在mac下吗？直接装上就能用？不用刷白名单？

**Comment by dfsnc** [comment]
没有白名单了，bcm94360cd可以免驱的，所以插上就能用

**Comment by dfsnc** [comment]
在windows下wifi有问题，搜不到网络

**Comment by recmess** [comment]
上面说的DW1820A，即能在mac下用也能在win下用？

**Comment by m4ak** [comment]
不用刷白名单，需要有个引导参数，现在能识别就是驱动不上，驱动方法是按照小兵的教程做的，我看他的方法也是照国外论坛做的。1820a好像有5种序列号，最好的就是0vw3t3的，08kpf4的这个不好驱动------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年10月28日(星期一) 凌晨0:21
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



驱动不起来是指在mac下吗？直接装上就能用？不用刷白名单？
 
&mdash;

**Comment by m4ak** [comment]
嗯，我现在就用1820A win10 1903 wifi bt 都正常使用。mac下也能识别就是不加载驱动，不知道是不是我的操作不对------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年10月28日(星期一) 凌晨0:29
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



上面说的DW1820A，即能在mac下用也能在win下用？
 
&mdash;

**Comment by recmess** [comment]
> 嗯，我现在就用1820A win10 1903 wifi bt 都正常使用。mac下也能识别就是不加载驱动，不知道是不是我的操作不对------------------ 原始邮件 ------------------ 发件人: "recmess"<notifications@github.com> 发送时间: 2019年10月28日(星期一) 凌晨0:29 收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>; 抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1) 上面说的DW1820A，即能在mac下用也能在win下用？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你的1820a在双系统下是否都已正常使用？

**Comment by m4ak** [comment]
win10正常  mac下没驱动上，你驱动上了！------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年11月1日(星期五) 晚上11:03
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)


 
嗯，我现在就用1820A win10 1903 wifi bt 都正常使用。mac下也能识别就是不加载驱动，不知道是不是我的操作不对------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "recmess"notifications@github.com 发送时间: 2019年10月28日(星期一) 凌晨0:29 收&#x4EF6;人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com; 抄送: "cchyswy"1067669073@qq.com;"Author"author@noreply.github.com; 主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1) 上面说的DW1820A，即能在mac下用也能在win下用？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你的1820a在双系统下是否都已正常使用？
 
&mdash;

**Comment by m4ak** [comment]
我又淘了一个1820A，这个是0vw3t3 的，驱动一下，如果搞上，就可以用啦。周三到，我安装上给你回复，我qq 1067669073  可以的话加一下，这样沟通方便------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年11月1日(星期五) 晚上11:03
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)


 
嗯，我现在就用1820A win10 1903 wifi bt 都正常使用。mac下也能识别就是不加载驱动，不知道是不是我的操作不对------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "recmess"notifications@github.com 发送时间: 2019年10月28日(星期一) 凌晨0:29 收&#x4EF6;人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com; 抄送: "cchyswy"1067669073@qq.com;"Author"author@noreply.github.com; 主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1) 上面说的DW1820A，即能在mac下用也能在win下用？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你的1820a在双系统下是否都已正常使用？
 
&mdash;

**Comment by m4ak** [comment]
看你更新EFI了。你使用DW1820A了吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"recmess"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 晚上11:03
收件人:&nbsp;"EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com&gt;;
抄送:&nbsp;"HW"<1067669073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450S install 94360cd (#1)



 
嗯，我现在就用1820A win10 1903 wifi bt 都正常使用。mac下也能识别就是不加载驱动，不知道是不是我的操作不对------------------ 原始邮件 ------------------ 发件人: "recmess"notifications@github.com 发送时间: 2019年10月28日(星期一) 凌晨0:29 收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com; 抄送: "cchyswy"1067669073@qq.com;"Author"author@noreply.github.com; 主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1) 上面说的DW1820A，即能在mac下用也能在win下用？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你的1820a在双系统下是否都已正常使用？

**Comment by m4ak** [comment]
今天1820A 到货了，win下驱动正常使用蓝牙也可以，mac下驱动方法是按照黑果小兵的方法。clover 里＋引导参数，设备信息里写网卡参数强制加载80211驱动，按照这个做了一下，没驱动上。oc的方式不会啊，有空指点下一下啊。
---原始邮件---
发件人:"recmess"<notifications@github.com>
发送时间:2019年10月28日 星期一 上午0:29
收件人:"EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>
抄送:"cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)

上面说的DW1820A，即能在mac下用也能在win下用？

&mdash;

**Comment by recmess** [comment]
因为出差，我先搞了一个USB的黑苹果免驱WIFI，COMFAST WU811AC，支持5g和2.4g。

**Comment by m4ak** [comment]
https://koolshare.cn/thread-68770-1-1.html


看看这个关于94360的，这里的大神说94360CD挑驱动，说是可以用AUSU ac68的驱动，你可以试一下。


还有我现在重装的10.15,使用你的EFI。现在我有2块DW1820A ，不会搞驱动啊。有没有兴趣搞搞。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"recmess"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 晚上11:08
收件人:&nbsp;"EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com&gt;;
抄送:&nbsp;"HW"<1067669073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450S install 94360cd (#1)




因为出差，我先搞了一个USB的黑苹果免驱WIFI，COMFAST WU811AC，支持5g和2.4g。

**Comment by m4ak** [comment]
测试过1820a吗？
我现在尝试驱动这个但是一开始就卡住了。在kernel中➕了个17.指定网卡驱动位置。加上这个就卡白苹果了。不加这个 ，还能进系统。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"recmess"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 晚上11:08
收件人:&nbsp;"EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com&gt;;
抄送:&nbsp;"HW"<1067669073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450S install 94360cd (#1)




因为出差，我先搞了一个USB的黑苹果免驱WIFI，COMFAST WU811AC，支持5g和2.4g。

**Comment by recmess** [comment]
我看一些1820a的帖子，感觉还是不要花时间折腾了，昨天买了个BCM94360CS2+A/E转接卡，安装一次成功，WIFI/BT 10.15下免驱。但据说这个卡在win10下驱动有点困难，目前还没测试。但是也没关系，我还有一个USB的CF-811AC网卡，可以在win10下凑合用。
![WechatIMG1](https://user-images.githubusercontent.com/25577389/68852980-ee2e3480-0713-11ea-98aa-66a4f8434feb.jpeg)

**Comment by m4ak** [comment]
是啊，我搞了2个1820都不好搞驱动，而且他们说还不稳定。你这个94360CS2 是2天线的。看照片不需要ipex 的转接了。还有你的94360CD应该是驱动的事情，他们＋pci -e 的转接卡用在台式机上的好多。5g 能达到1300m  我准备买94360csax 3天线的，也弄个a/e 转接搞一下，免驱动了还省事。你的efi 没有3码今天把3码加上了，但是没声卡了，我看驱动目录有appale alc 的 驱动啊，把这个弄好就完美了，虽然休眠在我这不好用。我就强制不休眠了。------------------ 原始邮件 ------------------
发件人: "recmess"<notifications@github.com>
发送时间: 2019年11月14日(星期四) 晚上7:21
收件人: "EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi"<Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi@noreply.github.com>;
抄送: "cchyswy"<1067669073@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi] T450Sinstall 94360cd (#1)



我看一些1820a的帖子，感觉还是不要花时间折腾了，昨天买了个BCM94360CS2+A/E转接卡，安装一次成功，10.15下免驱。但据说这个卡在win10下驱动有点困难，目前还没测试。但是也没关系，我还有一个USB的CF-811AC网上，可以在win10下凑合用。
 
 
&mdash;
