### ISSUE TITLE
Earphone audio not working if system not start with earphone plugged

### ISSUE THREAD

**Issue by Zardinality** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#11]
If the system does not start with earphones plugged, the audio setting will only show the speaker as output, in which case the speaker works as normal. 
If the earphone is plugged before the system starts everything is fine(though the lowest but not the mute level of the volume is considerably loud to me, I would not consider it as an issue).

**Comment by dfsnc** [comment]
That might be a VoodooHDA problem, I suggest you use AppleALC.
To use AppleALC, enable kernel block "fix AppleALC" in my newly efi and use [ALCPlugFix](https://github.com/Sniki/ALCPlugFix) to fix ExtMic problem.

**Comment by crazyi** [comment]
It is alright for me to boot without pluging in the earphone while using VoodooHDA, and I think ALCPlugFix maybe the key solution.

**Comment by Zardinality** [comment]
@EchoEsprit Thanks for the advice. I used the newest EFI now and it should be using AppleALC. This problem still replicates, that's a weird one. Any other idea why it is that way?

**Comment by Zardinality** [comment]
Confirmed it is because I installed a `sunflower.kext` in the previous version system. Now everything is normal, I hereby close this issue.
