### ISSUE TITLE
stuck after choose usb partion on boot menu (F12-choose

### ISSUE THREAD

**Issue by vohuu298** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#12]
i cant boot into USB partition
boot menu appear again and again when i choose USB open core partition
pls help

**Comment by dfsnc** [comment]
What do you mean "boot menu"?
Can you take a picture?

**Comment by vohuu298** [comment]
boot menu show up when press F12
can you write some instruction about creating opencore usb with catalina on T450s
i really like hackintosh, but with limitation about programming, i tried then failed
plz help

**Comment by vohuu298** [comment]
i finally figure out my fault. i will comment here
