### ISSUE TITLE
miniDP接口输出正常

### ISSUE THREAD

**Issue by sdwfyzz** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#13]
![image](https://user-images.githubusercontent.com/48829233/67944823-7bd73380-fbee-11e9-8785-b0a963e62f2a.png)
未接外置显示器
![image](https://user-images.githubusercontent.com/48829233/67944899-af19c280-fbee-11e9-8b22-f2bf7d919df6.png)
接入显示器

**Comment by EchoEsprit** [comment]
感谢告知！
