### ISSUE TITLE
Dual boot

### ISSUE THREAD

**Issue by vohuu298** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#14]
Help me how to dual boot hackintosh with win 10 (win10 already installed)

**Comment by crazyi** [comment]
You can just install OC to the ESP and OC will automaticly detect the boot option for win10. Then you can add OC to your defaut boot tool with EasyEFI

**Comment by simprecicchiani** [comment]
Could you please be more specific about the process? Thanks

**Comment by gabgabe** [comment]
I'm trying to dual boot OS X on drive 1 and Win10 on drive 2

on OpenCore picker can see only OS X and OS recovery, but if try booting same OpenCore configuration from usb then I can see windows (but oc give me an error so can't boot win). 
What am I doing wrong? 
Help me I'm loosing my mind

Tried Installing windows in legacy and uefi, now using uefi. 

btw thank you very much, oc worked at first try, just had to adapt some config params to enable FileVault (actually disabled).


[Config.plist.zip](https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/files/4361237/Config.plist.zip)

**Comment by gabgabe** [comment]
Update: 
solved changing
Misc->Boot->HideSelf **FALSE**

But still have the error:

`OCB: start image failed - Already started
Halting on critical error`

Suggestions?
