### ISSUE TITLE
Disable trim

### ISSUE THREAD

**Issue by Zardinality** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#17]
This week I experienced an SSD breakdown when my laptop sleeps with this EFI. Although not guaranteed relevant, I would like to ask the way to disable trim in `config.plist`. 
I found a relevant term whose name is `ThirdPartyTrim `, is this ok to just set this item to `false`?

**Comment by i3p9** [comment]
Yes it’s okay. And yes you’re right about it disabling TRIM. 

According to OC Configuration guide it’s recommended to keep ThirdPartyTrim to false and enable it via trimforce.
