### ISSUE TITLE
T450s Wifi/BT card BCM94360CD

### ISSUE THREAD

**Issue by i3p9** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#2]
Hi I just saw that you used BCM94360CD card for your Hackintosh. I have the same laptop and I was wondering how did you connect the card to your laptop? Did you use an adapter? 

Can I use this card and adapter? https://www.aliexpress.com/item/32704591968.html

Thank you very much!

**Comment by dfsnc** [comment]
I used bcm94360cd with ngff adapter like [this](https://www.aliexpress.com/item/32860559726.html), and 4 * IPEX-4 Female to IPEX-1 Male like [this](https://www.ebay.com/itm/IPEX-4-IPEX-Gen4-UFL-Female-to-IPEX-1-Connector-Jack-Male-Pin-For-BCM94360HMB-/281963506281).
My card works perfectly under hackintosh, but I can't get it work on win10 or linux, thought you should know this  if you need to use win10 or linux on your t450s.

**Comment by i3p9** [comment]
@EchoEsprit Thank you!! So you used the antenna adapter to connect to the laptops antenna cables right? This is my T450s: https://i.imgur.com/IW77k4s.jpg it has two antennas connected to the Intel Wifi/BT right now. Do I use the red and blue wire as well?

I mean I don't use Windows/Linux and if everything works out then I'll only use hackintosh. Thanks for the warning friend! 

Do you have any other way to contact(email/wechat) about the wifi card installation and ssdt questions, I have never done it. 

I'm very used to Desktop Hackintosh but Laptop is a new thing to me.

**Comment by dfsnc** [comment]
BCM94360CD need to connect all four of the antennas.
My email: EchoHou@protonmail.com

**Comment by i3p9** [comment]
@EchoEsprit oh okay so I use the two unused antennas too. Thank you. I just ordered them. 


And as for the ssdt and config you made, do I need to make any modifications? (Other than generating serial/smbios)

I have the same model, i5 model and 12gb ram. Latest bios. Again thank you very much friend. I was very afraid.

**Comment by dfsnc** [comment]
Well, I think there is no need for any other modifications.
Let me know if you run into any issues.

**Comment by i3p9** [comment]
@EchoEsprit Oh okay. I have booted into installation phase so far and no problems. Will install it fully after the Wifi/bt card arrives.

You will update the EFI if there’s a new update or anything right?

**Comment by dfsnc** [comment]
Yeah, I will keep update.

**Comment by i3p9** [comment]
Thanks! And I opened my laptop to upgrade the RAM, and saw the current wifi card, and it seems to have very little space, was the card and adapter a tight fit in your machine?

**Comment by dfsnc** [comment]
It fits, You need to modify your adapter, make it shorter than 4360 card.

**Comment by i3p9** [comment]
Ah so I basically just need to keep the part where it connects to the card, everything else isn't needed at all? 

Oh and did you mod your BIOS? I’m on the latest bios version, it will work right? What’s your bios version? 

My bios: https://i.ibb.co/37gjt16/IMG-1300.png

**Comment by dfsnc** [comment]
My bios version is 1.36, latest version should work.
I made a guide on install wifi card, see [here](https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/blob/master/Install%20BCM94360CD%20on%20Thinkpad%20T450s.md)

**Comment by i3p9** [comment]
Oh wow thanks so much for the photos!

**Comment by dfsnc** [comment]
😄

**Comment by i3p9** [comment]
@EchoEsprit So I'm having trouble installing unfortunately. I booted from your EFI, then erased the disk as APFS, started installation process. After the first reboot, was stuck at apple logo for a while and then this appeared: https://i.imgur.com/ftkuF3h.jpg (Message: macOS couldn't be installed on your system, installer resources were not found). Rebooted and loaded installer again and got kernel panic: https://i.imgur.com/50GHgeQ.jpg

What am I doing wrong here? 

Notes: I have only the SSD installed, still using the Intel Wifi (bought a USB wifi dongle while the card arrives in the mail) 

One more thing: when I did `diskutil list` there was a ton of random small volumes like this: https://i.imgur.com/50GHgeQ.jpg (dev/diskX went upto disk23)

(tried to do via clover, same problem)

**Comment by dfsnc** [comment]
How are you creating the USB installer?
I recommend you to create your USB installer using [this](https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/macOS%20Catalina%2010.15%2819A583%29%20Installer%20for%20Clover%205096%20and%20WEPE.dmg) image with [balenaEtcher](https://www.balena.io/etcher/) and replace the efi.

**Comment by i3p9** [comment]
@EchoEsprit I did it via command line, the regular one that Apple has. I'll try to do it via balenaEtcher. The same dmg I used for my desktop and it worked ;( 

I'm on mobile internet now so I'll try to use the current DMG file that I have (downloaded from my macbook) 

Also edited my previous post about a disk issue when I did `diskutil list`

**Comment by dfsnc** [comment]
You can use my clover [efi](https://drive.google.com/open?id=1nfFR0LC5cNgQeUvdOpTYhOfT_L_2LZFS)  temporarily, once you successfully installed your system,  replace it with my opencore efi.

**Comment by i3p9** [comment]
@EchoEsprit trying that right now. 

Although I have a thought. When I did disutil list while trying to format the drive, there was random small disk3 to disk23 (as disk image) in my computer. I have no idea what they are. https://i.imgur.com/oUki5eW.jpg

When I googled my problem, most solutions were to plug out all the other drives in the computer. Do you think those random disk3 to disk23 were the ones causing problems?

**Comment by dfsnc** [comment]
I'm not sure, but I don't think they were the reason of this issue.

**Comment by i3p9** [comment]
@EchoEsprit then it's weird. I'm downloading the dmg you provided since it probably worked for you. It'll take some time.

Meantime I'm trying with your EFI. It's taking some time because erasing to APFS sometime gets stuck and I have to reboot the installer again. 

If I still have the same issue, while your DMG downloads, I'll try this too: https://www.tonymacx86.com/threads/solved-macos-could-not-be-installed-on-your-computer-installer-resources-error.263961/page-3

**Comment by dfsnc** [comment]
That's weird. I've never encountered this situation.

There is another way, you can backup your macbook's system to an external drive  with time machine, then use my efi on your USB installer, once booted into the installer, you can recover the time machine bakup from your external drive.

That should work, because I installed my hackintosh using the same method.

**Comment by i3p9** [comment]
@EchoEsprit Yeah I'm very frustrated, weird issue. 

So I already have Time Machine setup: 
![image](https://user-images.githubusercontent.com/8825262/67620366-d572e300-f827-11e9-87dc-193b186dbc2f.png)

So I take the drive out, put in the laptop and while installing I do Time Machine Backup restore?

**Comment by dfsnc** [comment]
Yes, and when it's done, you move the efi from your USB installer into your system drive.

**Comment by i3p9** [comment]
@EchoEsprit I'll try that soon. 

alternatively, can I take out the SSD from the laptop, plug it in my Desktop, install normally, then put the ssd back into the laptop and boot using USB EFI?

**Comment by dfsnc** [comment]
That might work, you can try.

**Comment by i3p9** [comment]
Huh it worked. Cloning my drive worked and it booted. Wired. 

Now I’m wondering if updates might break the installation :/

**Comment by dfsnc** [comment]
Update won't break the installation, I've updated my system from mojave.

**Comment by i3p9** [comment]
No I meant that if I install macOS from a desktop, use the EFI on the laptop to run it, won't it break if an update comes? 

Since I can't clean install macOS on this laptop. That resources not found error appears every time. I've tried MANY combinations so far. I have no idea what's going on.

**Comment by dfsnc** [comment]
I’ve tried a clean install, and it’s ok.

**Comment by dfsnc** [comment]
Here is how I install.
first, you boot into the installer, erase your disk.
![01](https://user-images.githubusercontent.com/25398223/67629157-65a73b80-f8ad-11e9-9e8a-a0c9ec4ec0cc.JPG)
![02](https://user-images.githubusercontent.com/25398223/67629160-7952a200-f8ad-11e9-92b2-a5d39316863e.JPG)
![03](https://user-images.githubusercontent.com/25398223/67629161-79eb3880-f8ad-11e9-9926-09a1080655a9.JPG)
![04](https://user-images.githubusercontent.com/25398223/67629162-79eb3880-f8ad-11e9-8a0e-e691fbf8acb8.JPG)
then, install. this step just copy the installer into your disk, it will reboot.
![05](https://user-images.githubusercontent.com/25398223/67629163-7a83cf00-f8ad-11e9-9ce0-168d75880ab0.JPG)
![06](https://user-images.githubusercontent.com/25398223/67629164-7a83cf00-f8ad-11e9-8aae-c6a7c2a3883b.JPG)
![07](https://user-images.githubusercontent.com/25398223/67629165-7b1c6580-f8ad-11e9-829f-a0369473dfb4.JPG)
choose "macOS Installer" entry.
![08](https://user-images.githubusercontent.com/25398223/67629166-7b1c6580-f8ad-11e9-9e0e-46be2d38ca32.JPG)

here may look like it's not responding, just wait.
![09](https://user-images.githubusercontent.com/25398223/67629168-7b1c6580-f8ad-11e9-82d8-44619134c0fa.JPG)
![10](https://user-images.githubusercontent.com/25398223/67629169-7bb4fc00-f8ad-11e9-98ff-1f6d3f35889d.JPG)

**Comment by i3p9** [comment]
Thank you so much for you detailed instructions! You are amazing. 

The issue I'm having is that everything works like your photo, but the `x minutes remaining` doesn't appear at all. 

I think it's because during the second reboot, for some reason the ssd apfs isn't being mounted. See image here: 
![IMG_2718](https://user-images.githubusercontent.com/8825262/67633971-dca9f780-f8e0-11e9-8717-c83d6a9146b8.jpg)

And that's why after the installer is copied to the ssd in the first stage, it can't run, and giving me the error of resource not found, as the resource is in the ssd and it isn't being mounted. 

![image](https://user-images.githubusercontent.com/8825262/67634006-15e26780-f8e1-11e9-94e3-5ab60b96d83f.png)


But the problem is, when I used the same SSD and put it in my Desktop computer, it runs fine.

**Comment by i3p9** [comment]
I got it working somehow. Had to use another computer do the second part of installation. 

So which flags do you change in opencore to remove verbose boot?

**Comment by dfsnc** [comment]
I'm sorry that I couldn't help you with this.

You can remove verbose boot by delete "-v debug=0x100 keepsyms=1".

**Comment by i3p9** [comment]
No no it's totally okay. I think its my ssd fault. And you have helped a TON.

I have everything running now. Although audio is way too low for me. Does using AppleALC increase the volume? 

And when I add AppleALC, I also need to add layout-id to device properties as well right? 

Edit: For AppleALC, I put the kext inside the OC/kext folder:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/8825262/67637330-acc01b80-f903-11e9-8c7a-94d0652c94f7.png">


Then I edited the config, disabled VooDooHDA and added AppleALC: 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/8825262/67637305-5fdc4500-f903-11e9-9cd1-757c8359fb87.png">

Then I added layout-id like this: 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/8825262/67637321-92863d80-f903-11e9-81aa-44578dcbbe7d.png">

It should work right? Unfortunately it's not.

**Comment by dfsnc** [comment]
layout-id type should be "data"(4 byte) type (0x20000000).
and you need [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/blob/master/ALCPlugFix) to fix unworking jack after replug. (It's still not perfect enough...)

I've fixed this volume issue in my new update.

**Comment by i3p9** [comment]
@EchoEsprit since the volume is much louder (although it was even louder in Windows, that's okay tho) I'm gonna stick with it. Oh and do you know if using [this](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-Thinkpad_Trackpad.dsl) would increase the scrolling speed of two finger scrolling? 

Microphone isn't working unfortunately. Oh and I tested VGA since you had it listed as Untested, it's not working. I don't ever use VGA but wanted to test for you.

**Comment by dfsnc** [comment]
I used SSDT-Thinkpad_Clickpad, the "Trackpad" one will make the trackpoint (redpoint) too slow.

Microphone should work, check System Preferences -> Sound -> Input, choose the "Digital" one, that's the internal microphone, the "Black Right" one would work only when you plug in an earpiece with microphone.

**Comment by i3p9** [comment]
@EchoEsprit If I don't use the Redpoint at all, can I replace the Clickpad one with the SSDT-Thinkpad_Trackpad.dsl one? Will that make scrolling better?

And up the Mic works, but even with the Input volume set to 1% only, the mic is wayy too sensitive and records noise. Where can we change the sensitivity of the mic? 

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/8825262/67659862-a1163880-f987-11e9-9e39-9ed1bac2075b.png">

See here the input level is almost full even with input volume/sensitivity set to low and it records a blob.

**Comment by dfsnc** [comment]
Since VoodooHDA is having lots of issues, I've been trying to use AppleALC, but I found out that I could't get it work at all...
It works with clover, when you set `FixTMR` to true, but with opencore, I don't know how to fixit.

**Comment by i3p9** [comment]
@EchoEsprit same here. I’ve tried to get AppleALC to work multiple times last night, no dice. 

I’ve switched back to your voodoohda setup for now. 

I also need to test rehabman’s trackpad aml file too. 


Oh one thing, there’s no way to get three finger gestures with Rehabman’s kext right?

**Comment by dfsnc** [comment]
There is a temporarily solution for AppleALC, https://github.com/acidanthera/bugtracker/issues/422

I updated the efi with a new VoodooPS2 from https://github.com/acidanthera/bugtracker/issues/418#issuecomment-547674864, and now three buttons and three finger gestures are both working.
This is the download link https://github.com/acidanthera/bugtracker/files/3786222/VoodooPS2Controller.kext.zip

**Comment by i3p9** [comment]
@EchoEsprit that works wonderfully, awesome thanks <3 


I saw your AnyAppleUSBMouse kext and wondering if I could use them on my desktop setup. 
My mouse pid/vid is here: 
![image](https://user-images.githubusercontent.com/8825262/67853120-10328f00-fb38-11e9-90a8-1537e0bf8404.png)

and in the kext the id are in normal decimal value it looks like? 
![image](https://user-images.githubusercontent.com/8825262/67853187-30fae480-fb38-11e9-9833-61213e5f5f3c.png)

so what do I put there, the hex values directly?

**Comment by crazyi** [comment]
@i3p9 There is also an alternative for the wifi/bt card BCM94352Z, it is a ngff card which is a perfect match to T450s. The only issue is the same to BCM94360CD with the wifi problem on Windows.
Hope someone can fix this issue and hackintosh for T450s will be wonderfull.

**Comment by i3p9** [comment]
@crazyi which card are you talking about? Link?

I don’t use Windows/Linux at all. So thankfully I don’t have to worry about the driver issues

**Comment by crazyi** [comment]
@i3p9 This the card link on aliexpress. https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20191106051306&SearchText=DW1560

**Comment by steelcg** [comment]
Because i plug a SSD driver to m.2 interface, I wonder i can remove the original WIFI card and plug the BCM94360CD to the same interface. Thank you!

**Comment by i3p9** [comment]
@EchoEsprit I didn't know where to contact you but here, I just saw your commits and you changed the Product from MacBookAir to Macbook9,1, what's the benefit of doing that? Should I switch also? Cheer!

**Comment by dfsnc** [comment]
I gave you my email...
T450s with Macbook9,1 can enable HWP (Don't know if it's needed though) and Sidcar.

**Comment by i3p9** [comment]
Oh shoot I totally forgot. I even saved it in my address book. Sorry about that. 

Alright I guess I'll switch to Macbook9,1, Because sidecar would actually help me a lot. Using macbook won't cause any power issues right?

**Comment by dfsnc** [comment]
It's ok.
Notice that switch to Macbook9,1 can only use sidecar with wire connected to your ipad, wireless mode isn't working. And I've been using this config for a while, It seems fine.

**Comment by i3p9** [comment]
Ah cheers I'm changing to it right now. And for iMessage you keep the same Serial even if you change your ProductID right? I was wondering that might cause any issues with Apple. One serial, three products change.

**Comment by dfsnc** [comment]
You need to regenerate your SystemSerialNumber and MLB, and you might need to logout your appleid and relogin it after switch, otherwise iMessage might not work.

**Comment by i3p9** [comment]
Yeah I just remembered. Got everything setup, logged out of everything and booting in a sec. *fingers crossed*

**Comment by i3p9** [comment]
Welp everything is good. @EchoEsprit is sidecar a bit low res for you? the res is good but there's artifacts when moving something.

**Comment by dfsnc** [comment]
Emmmm...
I did reinstalled system while I'm testing dw1820a.
Is your ipad model support sidecar?

![image](https://user-images.githubusercontent.com/25398223/70025935-61bbb700-15d9-11ea-9757-6c2884329d53.png)

**Comment by i3p9** [comment]
Yes I have the latest iPad Pro 11" and iPad Air 3rd gen and it both supports Sidecar. The problem looks more like the iPad can't stream properly when using sidecar.

Here's a short video of the problem I'm facing: https://streamable.com/4iysv

Oh wait so you got DW1820A working? I've seen there's multiple version of that card, and most of them doesn't work properly. Which exact one did you buy?

**Comment by dfsnc** [comment]
Mine is Lenovo's 00JT494.
Actually this is not the only version that works on t450s, as far as I know Dell's CN-096JNT also works.

**Comment by i3p9** [comment]
So like something like this? https://www.aliexpress.com/item/33005108053.html 
Does it need additional antenna adapters? 

Also did you look at the sidecar video that I posted?

**Comment by dfsnc** [comment]
Yes, It doesn't need any adapter.

Video is still loading......  😓

**Comment by dfsnc** [comment]
The problem you're talking about might because 5th gen cpu doesn't support hevc decode.
It's display affect is horrible😅

**Comment by i3p9** [comment]
Yeah that's what I thought. I also have a 4th gen hackintosh that had the same issue. So that's why I use Duet Display. It's very fast and doesn't have that horrible display affects. :P 

Did you see the aliexpress link I posted? Will that one probably work?

**Comment by dfsnc** [comment]
I saw that, It's the same model with mine.
I can't promise, but it should work.

**Comment by i3p9** [comment]
No yeah I understand. Each hardware is like slightly different if it comes from AliExpress :D

**Comment by dfsnc** [comment]
Yeah, all dw1820a came from two factories, one is Foxconn another one is Lite-on, other model like 0vw3t3 may have multiple different sub id, but 00JT494 seems only have this one sub id (016b,075a), so it should work.

**Comment by i3p9** [comment]
Ah gotcha I might order one. The other one is still in transit :(
