### ISSUE TITLE
DW1820A 驱动方式和运行状态

### ISSUE THREAD

**Issue by m4ak** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#21]
恭喜成功的将BCM94360CD + A/E   切换到DW1820A(00JT494)，有几个问题请教一下：
1、网卡需不需要屏蔽针脚？如果需要屏蔽，是屏蔽的5针脚吗？（正面3个，背面2个。）
2、在win10及MAC下运行稳定吗？会概率重启、死机之类的吗？
3、5G频段下连接速率是867？进行过速度测试吗？
4、其他序列号的卡如0vw3t3 08kpf4的测试过吗？可以正常驱动和使用不。

**Comment by dfsnc** [comment]
1、不需要屏蔽
2、稳定，不会重启或死机
3、我这里带宽没那么多，不知道能不能867
4、没有，我没有那么多卡

**Comment by m4ak** [comment]
多谢，我试试我这个0VW3T3的能否正常。
