### ISSUE TITLE
关于无线网卡

### ISSUE THREAD

**Issue by Toifyx** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#24]
你好，我看了下笔记本的电脑配置，如下，是不是无线网卡配置不一样嘛？是否还需要更换 无线网卡，谢谢。

![image](https://user-images.githubusercontent.com/16380059/70593378-c7322800-1c17-11ea-9d8e-c24aa21d79db.png)

**Comment by dfsnc** [comment]
Intel的无线网卡无法驱动的，需要更换无线网卡。

**Comment by m4ak** [comment]
@EchoEsprit 你的1820a能分享个照片吗？我去买个一样的
