### ISSUE TITLE
关于苹果网卡的问题

### ISSUE THREAD

**Issue by CLAY-BIOS** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#25]
bcm94360cs2 和 bcm943224PCIETB2在win10系统下均无法正常使用 
win10系统搜索不到WiFi 已经排除驱动问题 
mac系统下可以正常使用
不知道bcm94360CD能否正常使用 用过的朋友说一下
![IMG_20191214_150130](https://user-images.githubusercontent.com/54008255/70845411-4bd7ad00-1e89-11ea-9115-e346df0cc3db.jpg)

**Comment by dfsnc** [comment]
t450s 白果卡在Win10下都用不了，macOS下正常。4360cd也是。
