### ISSUE TITLE
BCM94352z M.2 card problem on my T450s

### ISSUE THREAD

**Issue by crazyi** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#3]
Hi, I have a Broadcom BCM94352z M.2 card (DELL DW1560), it works fine in my T450s on Catalina with Clover, but it also failed on Windows 10.
Here is someone solve the problem on Ubuntu (https://www.insanelymac.com/forum/topic/307738-bcm94352-working-in-osx-but-not-in-windowsoo/?page=2), simply add pci=irqpoll in the grub (or you preferred bootloader) kernel line.
Do you have any idea to fix this problem on Windows? @EchoEsprit 
Sorry to open a new issue as the last one was closed, and I thought I had the same issue with  your BCM94360CD card, not working on Windows.

**Comment by i3p9** [comment]
@crazyi have you tried this driver? https://support.lenovo.com/gb/en/downloads/ds103388

And for your DW1560, was it a tight fit? And did you need to do any modification to make it work in Catalina, or did it work OOB?

**Comment by dfsnc** [comment]
Some Wifi card works perfectly on macOS, but not on Windows.
see [here](https://www.tonymacx86.com/threads/wip-guide-hp-envy-x360-13-y013cl-i7-7500u-kaby-lake.213327/page-17#post-1609866)

**Comment by crazyi** [comment]
@i3p9 Yes, DW1560 is perfect in size with T450s, and worked well in macOS and Linux, the only thing is the windows driver issue. 

> many users confirmed that disabling "Wake On Magic Packet" and "Wake on Pattern Match" resolved the Windows 10 crashes.


The Moderator on tonymacx86 jaymonkey commented above maybe help to fix the issue, but I can not find the way to disable them.

**Comment by i3p9** [comment]
@crazyi do you need any additional kexts to run DW1560? Because BCM94360CD card with an adapter doesn't need any kexts to run which is better for the long term.

**Comment by crazyi** [comment]
> @crazyi do you need any additional kexts to run DW1560? Because BCM94360CD card with an adapter doesn't need any kexts to run which is better for the long term.

@i3p9 Yes, I add 3 kexts from acidanthera's BrcmPatchRAM, they are 1. BrcmFirmwareData.kext, 2. BrcmBluetoothInjector.kext and 3. BrcmPatchRAM3.kext. The order in the OC's config.plist must be the same as I post, or it will boot with some kernel panic.

**Comment by i3p9** [comment]
Ah cheers. Then I might go for BCM94360CD as it works oob, even though it needs an adapter. I think it might be a better choice because it doesn't need any kexts, one less thing to worry about when updating. 

I'm not sure which one to pick lol

**Comment by crazyi** [comment]
@i3p9 Sorry, I forgot to mention that AirportBrcmFixup.kext was also needed to enalbe wifi

**Comment by simprecicchiani** [comment]
Hi, I was wondering if these problems could be solved with a bcm94360cs2 card.
I have 2 of them on 2 different desktops mounted on pci-e adapters and they work either on MacOS and Win10.
I will soon get my hands on a T450s and I found this convenient kit from AliExpress: https://www.aliexpress.com/item/32849682011.html?spm=a2g0o.cart.0.0.3c493c00ScvAKK&mp=1
Do you know if there are any problems with it mounted on laptops?
Also, this card has only 2 antennas so there shouldn’t be additional labour to get it work (just wondering).

**Comment by doctorsoffix** [comment]
Can you send youre efi ?
