### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by doctorsoffix** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#33]
Hey, I have noticed that the battery percentage is always at 100 % even when in windows it is 40 % ( I am using dual boot with second m2 ssd ) how can I fix that ?

**Comment by doctorsoffix** [comment]
Edit : I use 2 batteries and even if I tAKE OUT ONE BATTERY IT STILL SHOWS 100 %

**Comment by dfsnc** [comment]
Solved in latest commit.
