### ISSUE TITLE
OCUI: Failed to locate valid png file - 0!

### ISSUE THREAD

**Issue by quanuanc** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#34]
## 问题描述
把EFI放入U盘引导10.15安装程序，出现以下画面：
![C97FC9F7D38105FE37B59FDD331E7E94](https://user-images.githubusercontent.com/37785611/74408957-acc33780-4e70-11ea-84bd-073ec5d1cf22.png)

**Comment by dfsnc** [comment]
看一下efi/oc/icons/new里有没有install.png

**Comment by quanuanc** [comment]
有的。

**Comment by dfsnc** [comment]
也许是图标文件受损了，你可以试着重新下载替换进去，或者换回官方版OC
