### ISSUE TITLE
Low sound 

### ISSUE THREAD

**Issue by ahalsaqqa** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#4]
Hello thank you very much for this t450s catalina EFI 

it's working perfectly on my t450s  i5-5300u  12gb ram  256 GB ssd  

but the sound from the laptop is very low comparing on windows

**Comment by dfsnc** [comment]
Here are some solutions.
[Audio volume is lower than normal with VoodooHDA](https://www.reddit.com/r/hackintosh/comments/489vh2/audio_volume_is_lower_than_normal_with_voodoohda/)
[Volume Too Low (half volume fix not working)](https://www.insanelymac.com/forum/topic/311970-volume-too-low-half-volume-fix-not-working/)

**Comment by dfsnc** [comment]
I've fixed this issue in my recent update, you should try it.
