### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by sam-anam1** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#44]
Hello @EchoEsprit we all hope you're fine! :)

please can you update this repositories to open core 0.5.9?
it seem there are a hug update on opencore

**Comment by i3p9** [comment]
@sam-anam1 updated in my fork. Check my profile.

**Comment by sam-anam1** [comment]
> @sam-anam1 updated in my fork. Check my profile.

Hello
everything is working with 10.15.7 and including windows boot option that's great. thank you so much!  i appreciate it!
