### ISSUE TITLE
Redpoint/Mojave efi

### ISSUE THREAD

**Issue by recmess** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#5]
1、怎样修复小红点使用？一直习惯用它，
2、用了EFI，10.15一切正常。但由于32位的问题，还是想退回mojave。能否提供10.14的EFI？谢谢
3、如何设置机型

**Comment by dfsnc** [comment]
1. 已修复
2. 应该同样适用10.14，我当时直接从10.14 升级的系统。
3. 机型已经设置好，不需要再设置机型，只需要自己生成序列号填入config即可。

**Comment by recmess** [comment]
我又下载安装了，红点和触摸板都可以移动光标，但上下两排左右按键都没反应。

**Comment by dfsnc** [comment]
把ApplePS2Controller.kext换成Rehabman的就可以了
Acidanthera版ApplePS2Controller支持三指手势，不支持触摸板按键
Rehabman版支持触摸板按键不支持三指手势

**Comment by recmess** [comment]
你说的是kexts/VoodooPS2Controller.kext?

**Comment by dfsnc** [comment]
是的，你可以在[这里](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/)下载Rehabman的ApplePS2Controller

**Comment by recmess** [comment]
下载了替换了，按键可以用了，但启动的时候有个错误，我截了个图
![WechatIMG4](https://user-images.githubusercontent.com/25577389/67617364-101f5000-f815-11e9-8bf6-ff485d56f1e7.jpeg)

**Comment by dfsnc** [comment]
下载我刚更新的efi吧，我修改了kext，现在不会报错了

**Comment by recmess** [comment]
非常感谢！

**Comment by dfsnc** [comment]
😄
