### ISSUE TITLE
节能要怎样设置，唤醒后才不会黑屏

### ISSUE THREAD

**Issue by recmess** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#7]
昨天晚上合上屏幕，早上打开后就黑屏，强行重启后提示电脑出现问题，要发送apple。这个我现在的设置
![截屏2019-10-27上午9 26 45](https://user-images.githubusercontent.com/25577389/67628224-c8440b80-f89c-11e9-8719-153916996d20.png)
![截屏2019-10-27上午9 33 57](https://user-images.githubusercontent.com/25577389/67628235-ee69ab80-f89c-11e9-98df-0d321f7a777d.png)

**Comment by dfsnc** [comment]
去掉唤醒以供以太网访问和电能小憩，这两个会导致唤醒黑屏。

**Comment by recmess** [comment]
谢谢，我试试
