### ISSUE TITLE
生成序列号碰到一个问题

### ISSUE THREAD

**Issue by recmess** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#8]
下了个OpenCore configurator打开config.plst，生成了四个号
![截屏2019-10-27下午9 07 04](https://user-images.githubusercontent.com/25577389/67635102-e1c96f80-f8fd-11e9-961d-d610b97d6ab7.png)

但在启动时，有两行错误，请问是哪里操作不对？谢谢！
![1572180609276](https://user-images.githubusercontent.com/25577389/67635128-1ccba300-f8fe-11e9-8aff-0a6c8c993ff3.jpg)

**Comment by crazyi** [comment]
明显是你的config.list有语法错误，用xcode对着改吧

**Comment by dfsnc** [comment]
我的config里根本没有PowerTimeoutKernelPanic和ReconnectOnResChange项，我用的这一版官方手册里甚至都没有ReconnectOnResChange，是你用OpenCore configurator打开导致配置文件语法出错的。
所以不建议使用OpenCore configurator。

**Comment by recmess** [comment]
非常感谢两位提醒，第一次用QC...
