### ISSUE TITLE
为什么要禁用 Intel Virtualization Technology

### ISSUE THREAD

**Issue by recmess** [EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi#9]
在BIOS里禁用后 虚拟机parallels desktop 没法用啊。我现在打开这个功能了，虚拟机可以用了，会影响到系统的稳定吗？

**Comment by dfsnc** [comment]
经过测试，Intel Virtualization Technology这个功能可以开启，需要关闭 Vt-d。

**Comment by recmess** [comment]
thanks!
